"""add budget routing

Revision ID: 22eecec0f92c
Revises: 8029274eb7c6
Create Date: 2026-03-26 17:24:07.125170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22eecec0f92c'
down_revision: Union[str, Sequence[str], None] = '8029274eb7c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routing_targets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ledger_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_routing_targets_ledger_id', 'ledger', ['ledger_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routing_targets', schema=None) as batch_op:
        batch_op.drop_constraint('fk_routing_targets_ledger_id', type_='foreignkey')
        batch_op.drop_column('ledger_id')

    op.create_table('_alembic_tmp_account_terms',
    sa.Column('account_name', sa.VARCHAR(), nullable=False),
    sa.Column('apr', sa.FLOAT(), nullable=False),
    sa.Column('min_payment', sa.FLOAT(), nullable=False),
    sa.Column('display_name', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('account_name')
    )
    # ### end Alembic commands ###
