"""Add triage and routing models

Revision ID: 8029274eb7c6
Revises: 887edf67dbc7
Create Date: 2026-03-25 17:08:55.273881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8029274eb7c6'
down_revision: Union[str, Sequence[str], None] = '887edf67dbc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_account_terms')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_account_terms',
    sa.Column('account_name', sa.VARCHAR(), nullable=False),
    sa.Column('apr', sa.FLOAT(), nullable=False),
    sa.Column('min_payment', sa.FLOAT(), nullable=False),
    sa.Column('display_name', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('account_name')
    )
    # ### end Alembic commands ###
